//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial3Movil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMensaje
    {
        public long DetalleMensajeId { get; set; }
        public Nullable<long> MensajeId { get; set; }
        public string MensajeDescripcion { get; set; }
        public int CostoId { get; set; }
        public long Remitente { get; set; }
    
        public virtual Costo Costo { get; set; }
        public virtual Telefono Telefono { get; set; }
        public virtual Mensaje Mensaje { get; set; }
    }
}
